name: Deploy Java Artifacts to GitHub Packages .

on:
  workflow_call:
    secrets:
      GH_PACKAGES_TOKEN:
        description: 'Token de autenticação do GitHub'
        required: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Download Java artifacts
        uses: actions/download-artifact@v4
        with:
          name: java-artifacts

      - name: Configurar Maven settings.xml para GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Configurar distributionManagement no pom.xml
        run: |
           xmlstarlet ed -L \
            -s "/project" -t elem -n "distributionManagement" -v "" \
            -s "/project/distributionManagement" -t elem -n "repository" -v "" \
            -s "/project/distributionManagement/repository" -t elem -n "id" -v "github" \
            -s "/project/distributionManagement/repository" -t elem -n "name" -v "GitHub Packages" \
            -s "/project/distributionManagement/repository" -t elem -n "url" -v "https://maven.pkg.github.com/${GITHUB_REPOSITORY}" \
            pom.xml

      - name: Deploy para o GitHub Packages
        run: mvn deploy -DskipTests
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}




