name: Deploy Java Artifacts to GitHub Packages .

on:
  workflow_call:
    secrets:
      GH_PACKAGES_TOKEN:
        description: 'Token de autenticação do GitHub'
        required: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Download Java artifacts
        uses: actions/download-artifact@v4
        with:
          name: java-artifacts

      - name: Configurar Maven settings.xml para GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml
           
      - name: Deploy para o GitHub Packages
        run: mvn deploy -DskipTests
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}




