on:
  workflow_call:
    inputs:
      build_configuration:
        description: 'Configuração de build (Debug ou Release)'
        required: true
        default: 'Release'
        type: string
jobs:
    checkout:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout código
          uses: actions/checkout@v4

        - name: dowload java artifacts
          uses: actions/download-artifact@v4
          with:
           name: java-artifacts

        - name: Configurar Github Packages
          run: mvn deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - name: Build da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
   
    
      
   
