name: Deploy Java Artifacts to GitHub Packages .

on:
  workflow_call:
    secrets:
      GH_PACKAGES_TOKEN:
        description: 'Token de autenticação do GitHub'
        required: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Download Java artifacts
        uses: actions/download-artifact@v4
        with:
          name: java-artifacts

      - name: Configurar Maven settings.xml para GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Configurar distributionManagement no pom.xml
        run: 
          GITHUB_USER="${{ github.actor }}"
          GITHUB_REPO=$(basename -s .git `git config --get remote.origin.url`)
          POM_FILE="pom.xml"

          if grep -q "<distributionManagement>" "$POM_FILE"; then
            echo " O arquivo pom.xml já possui <distributionManagement>."
          else
            echo " Adicionando <distributionManagement> ao pom.xml..."
            sed -i '/<\/project>/i\
          <distributionManagement>\
            <repository>\
              <id>github</id>\
              <url>https://maven.pkg.github.com/'"$GITHUB_USER"'/'"$GITHUB_REPO"'</url>\
            </repository>\
          </distributionManagement>' "$POM_FILE"
                  fi
           
      - name: Deploy para o GitHub Packages
        run: mvn deploy -DskipTests
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}




