name: Java Reusable Pipeline

on:
  workflow_call:
    inputs:
      java_version:
        description: 'Versão do Java a ser usada'
        type: string
        required: true
        default: '17'
      maven_version:
        type: string
        description: 'Versão do Maven a ser usada'
        required: true
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}

      - name: Instalar Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: ${{inputs.maven_version}}

      - name: Executar testes (unitários e integração)
        run: mvn clean verify

      - name: Análise com SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ github.repository }} \
            -Dsonar.organization=${{ github.repository_owner }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

      - name: Build do projeto (gera JAR)
        run: mvn package

      - name: Mostrar localização do artefato gerado
        run: |
          echo "Arquivos gerados:"
          find target -type f \( -name "*.jar" -o -name "*.war" \)

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-artifacts
          path: |
            target/*.jar
            target/*.war

     